<template>
  <v-text-field
    :id="`${_uid}`"
    ref="moneyInput"
    v-model="displayValue"
    :autocomplete="autocomplete"
    :clearable="clearable"
    :dense="dense"
    :disabled="disabled"
    :flat="flat"
    :hide-details="hideDetails"
    :hint="hint"
    :label="label"
    :loading="loading"
    :name="`${_uid}`"
    :outlined="outlined"
    :persistent-hint="persistentHint"
    :readonly="readonly"
    :rules="rules"
    type="text"
    :width="width"
    @blur="onBlur"
    @click:clear="onBlur"
    @focus="onFocus"
    @input="onInput"
  />
</template>
<script src="./MoneyInputComponent.ts"></script>
